export const INITIAL_CLIENTS = [
  {
    id: '1',
    company: 'Cape Trade Imports',
    contact: 'Sarah van der Berg',
    email: 'sarah@capetrade.co.za',
    phone: '+27 82 345 6789',
    country: 'South Africa',
    status: 'Active',
    source: 'Referral',
    notes: 'Key account. Primarily sources homeware and textiles. Prefers WhatsApp for day-to-day communication.',
    openOrders: 3,
    lastActivity: '2026-06-15',
  },
  {
    id: '2',
    company: 'Harlow & Sons Ltd',
    contact: 'James Harlow',
    email: 'james@harlowandsons.co.uk',
    phone: '+44 7700 900123',
    country: 'United Kingdom',
    status: 'Pipeline',
    source: 'Outreach',
    notes: 'Initial call completed. Waiting on product brief for garden furniture range.',
    openOrders: 0,
    lastActivity: '2026-05-28',
  },
  {
    id: '3',
    company: 'Weber Handels GmbH',
    contact: 'Klaus Weber',
    email: 'k.weber@weberhandels.de',
    phone: '+49 30 1234 5678',
    country: 'Germany',
    status: 'Active',
    source: 'Website',
    notes: 'Repeat buyer, quarterly orders. Focused on electronics accessories and cable management.',
    openOrders: 1,
    lastActivity: '2026-06-10',
  },
  {
    id: '4',
    company: 'Afrique Sourcing SARL',
    contact: 'Fatima Benali',
    email: 'f.benali@afrique-sourcing.fr',
    phone: '+33 6 12 34 56 78',
    country: 'France',
    status: 'On Hold',
    source: 'Referral',
    notes: 'Budget freeze until Q3 2026. Resume outreach in August.',
    openOrders: 0,
    lastActivity: '2026-04-12',
  },
  {
    id: '5',
    company: 'Durban Wholesale Co.',
    contact: 'Rajesh Patel',
    email: 'r.patel@durbanwholesale.co.za',
    phone: '+27 31 987 6543',
    country: 'South Africa',
    status: 'Active',
    source: 'Referral',
    notes: 'Long-term client since 2023. Monthly standing orders for hardware and power tools.',
    openOrders: 2,
    lastActivity: '2026-06-17',
  },
]
