export const INITIAL_INVOICES = [
  {
    id: 'inv-1',
    invoiceNo: 'INV-001',
    clientId: '1',
    orderId: 'ord-1',
    status: 'Paid',
    issueDate: '2026-04-15',
    dueDate: '2026-05-15',
    currency: 'USD',
    lineItems: [
      { description: 'Ceramic dinner sets — 500 units', qty: 500, unitPrice: 20.00 },
      { description: 'Custom Pantone-matched packaging', qty: 1, unitPrice: 1500.00 },
      { description: 'Freight coordination & handling', qty: 1, unitPrice: 1000.00 },
    ],
    notes: 'Payment received in full via T/T. Thank you.',
  },
  {
    id: 'inv-2',
    invoiceNo: 'INV-002',
    clientId: '5',
    orderId: 'ord-2',
    status: 'Sent',
    issueDate: '2026-05-10',
    dueDate: '2026-06-10',
    currency: 'USD',
    lineItems: [
      { description: 'Cordless power drill sets — 200 units', qty: 200, unitPrice: 35.00 },
      { description: 'Screwdriver kit accessories — 200 units', qty: 200, unitPrice: 6.00 },
    ],
    notes: 'Shipment in transit. Payment due on delivery confirmation.',
  },
  {
    id: 'inv-3',
    invoiceNo: 'INV-003',
    clientId: '3',
    orderId: 'ord-3',
    status: 'Draft',
    issueDate: '2026-06-18',
    dueDate: '2026-07-18',
    currency: 'USD',
    lineItems: [
      { description: 'USB-C hubs — 1,000 units', qty: 1000, unitPrice: 6.00 },
      { description: 'Cable management kits — 200 units', qty: 200, unitPrice: 4.00 },
    ],
    notes: 'Awaiting QC sign-off before sending.',
  },
  {
    id: 'inv-4',
    invoiceNo: 'INV-004',
    clientId: '1',
    orderId: 'ord-4',
    status: 'Overdue',
    issueDate: '2026-04-28',
    dueDate: '2026-05-28',
    currency: 'USD',
    lineItems: [
      { description: 'Linen table runners — 600 units', qty: 600, unitPrice: 4.50 },
      { description: 'Linen napkin sets — 600 units', qty: 600, unitPrice: 2.50 },
    ],
    notes: 'Second reminder sent 5 June. Follow up required.',
  },
  {
    id: 'inv-5',
    invoiceNo: 'INV-005',
    clientId: '2',
    orderId: 'ord-5',
    status: 'Sent',
    issueDate: '2026-06-05',
    dueDate: '2026-07-05',
    currency: 'USD',
    lineItems: [
      { description: 'Sourcing fee — garden furniture range', qty: 1, unitPrice: 1500.00 },
      { description: 'Factory assessment & sampling coordination', qty: 1, unitPrice: 2000.00 },
    ],
    notes: 'Deposit invoice for ORD-005 sourcing engagement.',
  },
]
