export const INITIAL_ORDERS = [
  {
    id: 'ord-1',
    orderId: 'ORD-001',
    clientId: '1',
    reference: 'CTP-HW-2026-01',
    category: 'Homeware & Textiles',
    description: 'Ceramic dinner sets and decorative tableware, 500 units. Custom Pantone-matched packaging required.',
    value: 12500,
    origin: 'Guangzhou',
    status: 'Production',
    deadline: '2026-07-15',
    createdAt: '2026-04-10',
    notes: 'Sample approved 12 May. Factory confirmed production start 3 June.',
  },
  {
    id: 'ord-2',
    orderId: 'ORD-002',
    clientId: '5',
    reference: 'DWC-HT-2026-01',
    category: 'Hardware & Tools',
    description: 'Power drill sets and cordless screwdriver kits, 200 units.',
    value: 8200,
    origin: 'Shenzhen',
    status: 'Shipped',
    deadline: '2026-06-30',
    createdAt: '2026-03-22',
    notes: 'Shipped via sea freight. ETA Durban port 28 June. Bill of lading received.',
  },
  {
    id: 'ord-3',
    orderId: 'ORD-003',
    clientId: '3',
    reference: 'WHG-EA-2026-01',
    category: 'Electronics Accessories',
    description: 'USB-C hubs and cable management kits, 1,000 units. CE certification required.',
    value: 6800,
    origin: 'Dongguan',
    status: 'QC',
    deadline: '2026-07-30',
    createdAt: '2026-04-18',
    notes: 'Third-party QC inspection booked with SGS for 25 June.',
  },
  {
    id: 'ord-4',
    orderId: 'ORD-004',
    clientId: '1',
    reference: 'CTP-TXT-2026-02',
    category: 'Homeware & Textiles',
    description: 'Linen table runners and napkin sets, 1,200 units. Ivory and sage colourways.',
    value: 4200,
    origin: 'Hangzhou',
    status: 'Sampling',
    deadline: '2026-08-20',
    createdAt: '2026-05-30',
    notes: 'Awaiting sample set from two shortlisted factories.',
  },
  {
    id: 'ord-5',
    orderId: 'ORD-005',
    clientId: '2',
    reference: 'HSL-GF-2026-01',
    category: 'Outdoor Furniture',
    description: 'Powder-coated steel garden furniture sets (table + 4 chairs), 80 units.',
    value: 15000,
    origin: 'Foshan',
    status: 'Sourcing',
    deadline: '2026-09-30',
    createdAt: '2026-06-01',
    notes: 'Shortlisted 3 factories. Visits scheduled for July.',
  },
]
