export const INITIAL_SUPPLIERS = [
  {
    id: 'sup-1',
    name: 'Guangzhou Artisan Ceramics Co.',
    contactName: 'Chen Wei',
    wechat: 'chenwei_ceramics',
    phone: '+86 20 8765 4321',
    email: 'chen.wei@gz-ceramics.cn',
    location: 'Guangzhou',
    category: 'Homeware & Ceramics',
    moq: '200 units',
    leadTime: 35,
    paymentTerms: 'T/T 30%',
    verified: true,
    status: 'Active',
    ordersFulfilled: 8,
    lastUsed: '2026-06-10',
    notes: 'Reliable factory, consistent quality. Lead time extends to 45 days during CNY.',
  },
  {
    id: 'sup-2',
    name: 'Shenzhen TechLink Electronics',
    contactName: 'Li Jing',
    wechat: 'techlink_shen',
    phone: '+86 755 2312 8899',
    email: 'lijing@techlink-sz.com',
    location: 'Shenzhen',
    category: 'Electronics Accessories',
    moq: '500 units',
    leadTime: 21,
    paymentTerms: 'T/T 30%',
    verified: true,
    status: 'Active',
    ordersFulfilled: 5,
    lastUsed: '2026-06-18',
    notes: 'Strong CE/RoHS documentation. Fast turnaround on reorders.',
  },
  {
    id: 'sup-3',
    name: 'Dongguan Powermax Tools',
    contactName: 'Wang Fang',
    wechat: 'powermax_dg',
    phone: '+86 769 8801 2200',
    email: 'wangfang@powermax.cn',
    location: 'Dongguan',
    category: 'Hardware & Tools',
    moq: '100 units',
    leadTime: 28,
    paymentTerms: 'T/T 100%',
    verified: false,
    status: 'Active',
    ordersFulfilled: 3,
    lastUsed: '2026-05-14',
    notes: 'Competitive pricing. Factory audit pending — schedule before placing next order.',
  },
  {
    id: 'sup-4',
    name: 'Foshan Stellar Furniture',
    contactName: 'Zhang Hao',
    wechat: 'stellar_fshn',
    phone: '+86 757 2298 7766',
    email: 'zhang.hao@stellar-furniture.com',
    location: 'Foshan',
    category: 'Outdoor Furniture',
    moq: '50 sets',
    leadTime: 45,
    paymentTerms: 'T/T 30%',
    verified: true,
    status: 'Probation',
    ordersFulfilled: 1,
    lastUsed: '2026-04-02',
    notes: 'Delayed shipment on ORD-005 by 3 weeks without notice. On probation pending next order performance.',
  },
  {
    id: 'sup-5',
    name: 'Yiwu Goldstar Accessories',
    contactName: 'Zhou Min',
    wechat: 'goldstar_yw',
    phone: '+86 579 8512 3344',
    email: 'zhoumin@goldstar-yiwu.cn',
    location: 'Yiwu',
    category: 'Accessories & Packaging',
    moq: '1,000 units',
    leadTime: 14,
    paymentTerms: 'T/T 100%',
    verified: false,
    status: 'Blacklisted',
    ordersFulfilled: 2,
    lastUsed: '2025-11-20',
    notes: 'Supplied counterfeit CE markings on two separate orders. Do not engage. Legal review in progress.',
  },
  {
    id: 'sup-6',
    name: 'Hangzhou Silkweave Textiles',
    contactName: 'Xu Mei',
    wechat: 'silkweave_hz',
    phone: '+86 571 8803 6655',
    email: 'xu.mei@silkweave.cn',
    location: 'Hangzhou',
    category: 'Homeware & Textiles',
    moq: '300 units',
    leadTime: 30,
    paymentTerms: 'L/C',
    verified: true,
    status: 'Inactive',
    ordersFulfilled: 4,
    lastUsed: '2025-09-08',
    notes: 'No orders placed since Q3 2025. Good quality track record — re-engage for upcoming textile orders.',
  },
]
