-- Meridian Platform — email_approvals table
-- Paste into Supabase SQL Editor and click Run

create table if not exists email_approvals (
  id              uuid primary key default gen_random_uuid(),
  created_at      timestamptz not null default now(),
  from_email      text not null,
  from_name       text,
  subject         text,
  body_raw        text,
  intent          text check (intent in ('NEW_ENQUIRY', 'RFQ', 'STATUS_UPDATE', 'GENERAL')),
  client_id       uuid references clients(id) on delete set null,
  -- One-line summary of the enquiry, shown on the /approvals list — generated by Claude
  -- alongside the draft response and persisted so the page doesn't need to recompute it.
  summary         text,
  draft_response  text,
  status          text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'sent')),
  sent_at         timestamptz
);

create index if not exists email_approvals_status_idx on email_approvals (status);
create index if not exists email_approvals_client_id_idx on email_approvals (client_id);

-- This table is only ever read/written via Netlify functions using the service-role key
-- (see netlify/functions/_supabaseAdmin.js), so RLS stays enabled with no permissive
-- policies — the anon/authenticated roles get no access at all, by design.
alter table email_approvals enable row level security;
